name: NuGet Generation
permissions:
  contents: write
  pull-requests: write 
  packages: write
  
on:
  workflow_dispatch:
  pull_request:
      branches: [main, dev]
      types: [opened, edited, synchronize, closed]
jobs:
  build:
    runs-on: macos-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{github.token}}             
      - name: Install WASM Tools Workload
        run: dotnet workload install maui android maui-android
      - name: Build solution and generate NuGet package
        run: |  
          cd src
          dotnet build -c Release CommunityToolkit.Maui.sln
          cd ../src/CommunityToolkit.Maui.MediaElement/
          dotnet pack -c Release -o out --no-build
      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./src/CommunityToolkit.Maui.MediaElement/out/*.nupkg --skip-duplicate --no-symbols true
